pool:
  vmImage: 'ubuntu-latest'
trigger: none

steps:
- task: HelmDeploy@0
  displayName: Init
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=1

- task: HelmDeploy@0
  displayName: RampUp
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=5

- task: HelmDeploy@0
  displayName: RampDown
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=1

- task: HelmDeploy@0
  displayName: Delete
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: delete
    waitForExecution: true
    arguments: cy --namespace cy --wait