pool:
  vmImage: 'ubuntu-latest'
trigger: none
parameters:
  replicas: 5
  duration: 5

steps:
- task: HelmDeploy@0
  displayName: Install Deployment
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=1

- task: HelmDeploy@0
  displayName: RampUp browsers to ${{ parameters.replicas }}
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=${{ parameters.replicas }}

- script: |
    sleep ${{ parameters.duration }}
  displayName: Keep load for ${{ parameters.replicas }} seconds
     

- task: HelmDeploy@0
  displayName: RampDown
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=1

- task: HelmDeploy@0
  displayName: Delete
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: delete
    waitForExecution: true
    arguments: cy --namespace cy --wait