pool:
  vmImage: 'ubuntu-latest'
trigger: none
parameters:
  - name: replicas
    default: 5
  - name: duration
    default: 5

steps:
- task: HelmDeploy@0
  displayName: Install Cypress Browser Load Deployment
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=1

- task: HelmDeploy@0
  displayName: RampUp cypress browsers to ${{ parameters.replicas }}
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=${{ parameters.replicas }}

- script: |
    sleep ${{ parameters.duration }}
  displayName: Keep load for ${{ parameters.replicas }} seconds
     

- task: HelmDeploy@0
  displayName: RampDown to 0
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: upgrade
    chartType: filepath
    chartPath: kubernetes/cypress/helm
    releaseName: cy
    waitForExecution: true
    arguments: --namespace cy --install --wait --set replicas=0

- task: HelmDeploy@0
  displayName: Delete Cypress Browser Load Deployment
  inputs:
    connectionType: Kubernetes Service Connection
    kubernetesServiceEndpoint: committed
    command: delete
    waitForExecution: true
    arguments: cy --namespace cy --wait